development: 
  adapter: mysql
  host: localhost
  username: root
  password:
  database: sharehouse_dev 
test: 
  adapter: mysql
  host: localhost
  username: root
  password:
  database: sharehouse_test
